Wrapper for classification #38
tyiannak/multimodal_movie_analysis pull request #39
Opened 2021-01-29 17:12 UTC by apoman38

**What this PR does:**

Added a new file _wrapper.py._ This file receives an mp4 file as input and returns in which class it belongs to.

In the _train.py_ file removed the one-hot encoding of the labeled data and added the saving of the trained model.

In the _analyze_visual.py_ added saving feature extraction in .npy format (not only in .csv).

**How to QA:**

Run the script `python3 wrapper.py -f dataset/trump.mp4 -m SVM` where -f option is the name of the file and -m the saved model of the training algorithm. The script must return the class that the file belongs.

2021-01-29 17:19 UTC, tyiannak commented
So I guess I need to retrain the model as well right?

2021-01-29 17:22 UTC, apoman38 commented
Yes right, because in the previous version train.py didn't save models.

2021-01-29 21:51 UTC, tyiannak requested changes

2021-01-29 21:51 UTC, tyiannak commented on analyze_visual/train.py
>      x_all = scaler.fit_transform(x_all)
This is the wrong point to use the scaler and it causes a bug in wrapper. 
The scaler must be fitted on the training data and then used during evaluation. Also the scaler must be embedded in the model and saved in the file (and obviously loaded in the wrapper). 
Please @apoman38 fix this bug.

2021-02-01 08:55 UTC, tyiannak requested changes

2021-02-01 08:55 UTC, tyiannak commented on analyze_visual/wrapper.py
> +    videos_path = [item for sublist in videos_path for item in sublist]
Please check if this is a file or folder. If folder do what u'r doing now. If file, just run the wrapper on a single video

2021-02-02 13:30 UTC, merged